Import('env')

_SOURCES_CORE = env.Glob("core/*.S") + \
                env.Glob("core/*.c") + \
                env.Glob("core/*.cpp")
env.Prepend(CPPPATH=[env.Dir('core').srcnode(),
                     env.Dir('variants/standard').srcnode()])
env.ArduinoCore = lambda: _SOURCES_CORE
env.ArduinoLibrary = lambda: env.Library('arduino_core',_SOURCES_CORE)
