Import('env','options')

_SOURCES_CORE = env.Glob("core/*.S") + \
                env.Glob("core/*.c") + \
                env.Glob("core/*.cpp")
_SOURCES_CORE_API = env.Glob("core/api/*.S") + \
                env.Glob("core/api/*.c") + \
                env.Glob("core/api/*.cpp")
_SOURCES_VARIANT_NONA4809 = env.Glob("variants/nona4809/*.c")
_SOURCES_VARIANT_UNO2018 = env.Glob("variants/uno2018/*.c")

arduino_variants_dir = options.get('arduino_variants_dir','')
if arduino_variants_dir:
    env.Prepend(CPPPATH=env.Dir('variants/%s'%arduino_variants_dir).srcnode())

env.Prepend(CPPPATH=[env.Dir('.').srcnode(),
                     env.Dir('core').srcnode(),
                     env.Dir('core/api/deprecated').srcnode()])
env.ArduinoMegaCore = lambda: _SOURCES_CORE + _SOURCES_CORE_API

VARIANTS_SOURCE_DICT = {
    'nona4809': _SOURCES_VARIANT_NONA4809,
    'uno2018': _SOURCES_VARIANT_UNO2018,
}
env.ArduinoMegaVariant = lambda x : VARIANTS_SOURCE_DICT[x]
env.ArduinoMegaLibrary = lambda: env.Library('arduino_core',_SOURCES_CORE + _SOURCES_CORE_API)
