import os

def build_program(env):
    # print(env.Dump())
    env.IncludeLibrary('arduino',variant_dir='#build')
    env.Prepend(CPPPATH=['#appl/uno/blink'])
    return env.Program(
        target='blink',
        source=[
            env.Glob("*.c"),
            env.Glob("*.cpp"),
         ],
         LIBS=[
            env.ArduinoLibrary(),
         ]
        )


Import('env')
abs_path = r"C:\Program Files (x86)\Arduino\hardware\tools\avr"
gccavrdir = os.environ['GCCAVR'] = abs_path

cc = env.Clone(tools=['gcc','gccavr'],
               GCCAVRDIR = gccavrdir,
               LINKFLAGS='-Wl,-gc-sections -fuse-linker-plugin -lm')
cc.Prepend(CXXFLAGS='-mmcu=atmega328p '
           '-Os -fdata-sections -ffunction-sections -flto')
cc.Prepend(CCFLAGS='-mmcu=atmega328p '
                   '-Os -fdata-sections -ffunction-sections -flto')
cc.Prepend(CPPDEFINES={'F_CPU': '16000000L',
                        'ARDUINO': 10819,
                        'ARDUINO_AVR_UNO':1,
                        'ARDUINO_ARCH_MEGAAVR': 1,
                        'ARDUINO_ARCH_AVR':1,
                        })
app = build_program(cc)
hex = cc.Rom(app)
Alias('build', hex )
