import os

def build_program(env):
    env.IncludeLibrary('arduino',arduino_variants_dir='standard')
    env.Prepend(CPPPATH=['#appl/uno/blink'])
    return env.Program(
        target='blink',
        source=[
            env.Glob("*.c"),
            env.Glob("*.cpp"),
         ],
         LIBS=[
            env.ArduinoLibrary(),
         ]
        )


Import('env')
abs_path = r"C:\Program Files (x86)\Arduino\hardware\tools\avr"
gccavr_dir = os.environ['GCCAVR'] = abs_path

cc = env.Clone(tools=['gccavr'])
cc.SetGccAvrVersion('7.3.0')
cc.SetGccAvrENVPath(gccavr_dir)
cc.Prepend(LINKFLAGS='-Wl,-gc-sections -fuse-linker-plugin -lm')
cc.Prepend(CCFLAGS='-mmcu=atmega328p '
                   '-Os -fdata-sections -ffunction-sections -flto')
cc.Prepend(CXXFLAGS=cc['CCFLAGS'])
cc.Prepend(CPPDEFINES={'F_CPU': '16000000L',
                        'ARDUINO': 10819,
                        'ARDUINO_AVR_UNO':1,
                        'ARDUINO_ARCH_MEGAAVR': 1,
                        'ARDUINO_ARCH_AVR':1,
                        })
app = build_program(cc)
hex = cc.Rom(app)
Alias('build', hex )
